import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {SIGHT_COLORS,SIGHT_OPACITY} from '../src/bethlehem-stealth-palette.js';
const src=fs.readFileSync(new URL('../src/bethlehem-water.js',import.meta.url),'utf8');
function fixture(){const released=[];const removed=[];const elements=new Map();const $=id=>{if(!elements.has(id))elements.set(id,{style:{transform:'held'},hasPointerCapture:()=>true,releasePointerCapture:p=>released.push([id,p]),classList:{remove:cls=>removed.push([id,cls])}});return elements.get(id);};return{keys:new Set(['ShiftLeft','KeyE','Space']),touch:{x:1,z:1,crouch:true,action:true,sprint:true},heldPointers:{crouch:2,action:3,sprint:4},stickPointer:1,stonePending:true,$,released,removed};}
test('3D and radar share a cool high-opacity patrol color distinct from warning and alert',()=>{assert.equal(SIGHT_COLORS.patrol,'#246beb');assert.ok(SIGHT_OPACITY.patrol>=.30);assert.equal(new Set([SIGHT_COLORS.patrol,SIGHT_COLORS.suspicious,SIGHT_COLORS.alert]).size,3);for(const file of ['bethlehem-water-world.js','bethlehem-water-radar.js'])assert.match(fs.readFileSync(new URL('../src/'+file,import.meta.url),'utf8'),/from '\.\/bethlehem-stealth-palette\.js'/);});
test('finishing water fill releases action without standing up or cancelling held crouch',()=>{const c=fixture();const fn=src.slice(src.indexOf('function clearActionInput(){'),src.indexOf('function closeModal(){'));vm.runInNewContext(fn+';clearActionInput();',c);assert.equal(c.keys.has('KeyE'),false);assert.equal(c.keys.has('ShiftLeft'),true);assert.equal(c.touch.action,false);assert.equal(c.touch.crouch,true);assert.equal(c.heldPointers.crouch,2);assert.equal(c.heldPointers.action,null);assert.deepEqual(c.released,[['action',3]]);assert.match(src,/state\.phase==='return'&&previousPhase==='filling'\)clearActionInput\(\)/);});
test('full reset still clears keyboard, joystick and every pointer-owned button',()=>{const c=fixture();const fn=src.slice(src.indexOf('function clearInput(){'),src.indexOf('// Filling changes'));vm.runInNewContext(fn+';clearInput();',c);assert.equal(c.keys.size,0);assert.deepEqual(c.touch,{x:0,z:0,crouch:false,action:false,sprint:false});assert.equal(c.stickPointer,null);assert.equal(c.stonePending,false);assert.deepEqual(c.heldPointers,{crouch:null,action:null,sprint:null});assert.equal(c.released.length,4);});
