import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as battle from '../src/downfall-core.js';
const giant=(id,x,z)=>({id,sinId:'greed',x,z,hp:3,maxHp:3,radius:.88,flash:0,age:0});
const cutoff=({score=730,kills=5,x=0}={})=>{const s=battle.createBattle();s.player.x=x;s.player.hp=1;s.score=score;s.kills=kills;s.time=20;s.wave=4;s.enemies=[giant(100,x,0),giant(101,-18,0),giant(102,0,-17)];battle.stepBattle(s,.025);return s;};
const tick=(s,t)=>{for(let i=0;i<Math.ceil(t/.025);i++)battle.stepBattle(s,.025,{moveX:1,aimX:1,firing:true});};
test('exhaustion enters grace instead of defeat and snapshots score once',()=>{const s=cutoff();assert.equal(s.phase,'grace');assert.deepEqual(s.result,{score:730,kills:5,wave:4,time:20.025,maxCombo:0,shots:0,hits:0});assert.ok(Object.isFrozen(s.result));assert.equal(s.stones.length,0);});
test('all counters and player freeze while grace clears all enemies without awarding kills',()=>{const s=cutoff({x:18}),r=s.result,cut={score:s.score,kills:s.kills,time:s.time,shots:s.shots,hits:s.hits,x:s.player.x,z:s.player.z,hp:s.player.hp};assert.equal(s.phase,'grace');tick(s,1);assert.equal(s.result,r);assert.ok(s.graceRadius>0);tick(s,4);assert.equal(s.phase,'complete');assert.equal(s.enemies.length,0);assert.equal(s.stones.length,0);assert.equal(s.effects.length,0);assert.equal(s.result,r);assert.deepEqual({score:s.score,kills:s.kills,time:s.time,shots:s.shots,hits:s.hits,x:s.player.x,z:s.player.z,hp:s.player.hp},cut);});
test('zero-score run receives same complete grace ending',()=>{const s=cutoff({score:0,kills:0});tick(s,5);assert.equal(s.phase,'complete');assert.equal(s.result.score,0);assert.equal(s.result.kills,0);assert.equal(s.enemies.length,0);});
test('no fire dash or nextwave during grace or complete',()=>{const s=cutoff();for(const stage of ['grace','complete']){assert.equal(s.phase,stage);assert.equal(battle.fireStone(s,1,0),false);assert.equal(battle.dash(s,1,0),false);assert.equal(battle.beginNextWave(s),false);if(stage==='grace')battle.finishGrace(s);}});
test('skip is phase-gated idempotent and never changes the locked result',()=>{const fresh=battle.createBattle();assert.equal(battle.finishGrace(fresh),false);const s=cutoff(),r=s.result;assert.equal(battle.finishGrace(s),true);assert.equal(s.phase,'complete');assert.equal(s.enemies.length,0);assert.equal(s.result,r);assert.equal(battle.finishGrace(s),false);const done=structuredClone(s);tick(s,2);assert.deepEqual(s,done);});
test('grace uses clamped simulation dt, invalid dt cannot skip to ending',()=>{const s=cutoff();const before=structuredClone(s);for(const dt of [0,-1,NaN,Infinity])battle.stepBattle(s,dt);assert.deepEqual(s,before);battle.stepBattle(s,500);assert.equal(s.graceElapsed,.05);assert.equal(s.phase,'grace');});
test('restart has no inherited grace or score snapshot',()=>{const s=cutoff();tick(s,5);const next=battle.createBattle();assert.equal(next.phase,'playing');assert.equal(next.result,null);assert.equal(next.graceElapsed,0);assert.equal(next.graceRadius,0);assert.equal(next.score,0);assert.equal(next.player.hp,5);});

test('last Scripture keeps verified 1Cor15:57KRV wording and attribution',()=>{const html=readFileSync(new URL('../downfall.html',import.meta.url),'utf8');assert.ok(html.includes('<blockquote id="finalVerse">우리 주 예수 그리스도로 말미암아 우리에게 이김을 주시는 하나님께 감사하노니</blockquote>'));assert.ok(html.includes('고린도전서 15:57 · 개역한글 (1961)'));assert.ok(html.indexOf('id="resultStats"')<html.indexOf('id="finalScripture"'));assert.ok(html.indexOf('id="finalScripture"')<html.indexOf('id="continueBtn"'));assert.ok(html.includes('은혜로 사라진 적은 점수에 더하지 않습니다.'));});
