import test from 'node:test';
import assert from 'node:assert/strict';
import {SINS,RULES,waveRules,createBattle,stepBattle,fireStone,beginNextWave,dash} from '../src/downfall-core.js';
const advance=(s,seconds,input={})=>{for(let i=0;i<Math.ceil(seconds/.025);i++)stepBattle(s,.025,input);};
const enemy=(id,x,z,sinId='lust',hp=1)=>({id,x,z,sinId,hp,maxHp:hp,radius:.68,flash:0,age:0});
test('nine scripturally referenced sin labels and endless increasing quotas',()=>{assert.equal(SINS.length,9);assert.equal(new Set(SINS.map(s=>s.name)).size,9);for(const s of SINS)assert.match(s.reference,/[0-9]+:[0-9]+/);assert.deepEqual([1,2,3,4].map(w=>waveRules(w).count),[18,24,30,36]);assert.ok(waveRules(1001).count>waveRules(1000).count);});
test('same seed gives identical deterministic simulations',()=>{const a=createBattle(12),b=createBattle(12);advance(a,3,{moveX:1,firing:true});advance(b,3,{moveX:1,firing:true});assert.deepEqual(a,b);});
test('invalid and zero delta never advance; long delta capped',()=>{const s=createBattle(),before=structuredClone(s);for(const dt of [NaN,Infinity,-1,0])stepBattle(s,dt);assert.deepEqual(s,before);stepBattle(s,10);assert.equal(s.time,.05);});
test('normalized movement and dash stay in circular arena',()=>{const s=createBattle();s.player.invulnerable=100;advance(s,10,{moveX:1,moveZ:1});assert.ok(Math.abs(Math.hypot(s.player.x,s.player.z)-18)<.00001);dash(s,1,1);assert.ok(Math.hypot(s.player.x,s.player.z)<=18.00001);const b=createBattle();stepBattle(b,.05,{moveX:1,moveZ:1});assert.ok(Math.abs(Math.hypot(b.player.x,b.player.z)-.35)<1e-8);dash(b,1,1);assert.equal(dash(b,1,1),false);assert.ok(b.player.invulnerable>0);});
test('shot cooldown and zero aim block accidental shots',()=>{const s=createBattle();assert.equal(fireStone(s,0,0),false);assert.equal(fireStone(s,0,-1),true);assert.equal(fireStone(s,0,-1),false);advance(s,.25);assert.equal(fireStone(s,0,-1),true);assert.equal(s.shots,2);});
test('swept stone hits between frames, kills only once',()=>{const s=createBattle();s.enemies=[enemy(900,0,-2)];fireStone(s,0,-1);stepBattle(s,.05);assert.equal(s.kills,1);assert.equal(s.enemies.length,0);assert.equal(s.hits,1);advance(s,.2);assert.equal(s.kills,1);});
test('nearest target blocks rear target regardless of array order',()=>{const s=createBattle();s.enemies=[enemy(901,0,-2.5),enemy(900,0,-1.5)];fireStone(s,0,-1);stepBattle(s,.05);assert.deepEqual(s.enemies.map(e=>e.id),[901]);});
test('durable enemies require multiple stones; combo enables pierce',()=>{const s=createBattle();s.enemies=[enemy(900,0,-2,'greed',3)];fireStone(s,0,-1);stepBattle(s,.05);assert.equal(s.enemies[0].hp,2);assert.equal(s.kills,0);const b=createBattle();b.combo=10;b.comboTimer=3;b.enemies=[enemy(902,0,-1.5),enemy(903,0,-2.5)];fireStone(b,0,-1);stepBattle(b,.05);assert.equal(b.kills,2);});
test('missed stones expire and entity counts remain bounded',()=>{const s=createBattle();s.player.invulnerable=100;advance(s,45,{firing:true,aimX:1,aimZ:0});assert.equal(s.spawned,18);assert.ok(s.enemies.length<=18);assert.ok(s.stones.length<8);assert.ok(s.effects.length<30);});
test('contact invulnerability prevents instant exhaustion; grace freezes gameplay counters',()=>{const s=createBattle();s.enemies=[enemy(900,0,0),enemy(901,0,0)];stepBattle(s,.025);assert.equal(s.player.hp,4);stepBattle(s,.025);assert.equal(s.player.hp,4);s.player.hp=1;s.player.invulnerable=0;s.enemies=[enemy(902,s.player.x,s.player.z)];stepBattle(s,.025);assert.equal(s.phase,'grace');const before=s.result;stepBattle(s,1,{firing:true});assert.equal(s.result,before);assert.equal(s.time,before.time);assert.equal(s.shots,before.shots);assert.equal(fireStone(s,1,0),false);assert.equal(dash(s,1,0),false);});
test('clearing waves never wins and next-wave gate works beyond original finale',()=>{const s=createBattle();assert.equal(beginNextWave(s),false);for(let wave=1;wave<=20;wave++){s.spawned=waveRules(wave).count;s.waveKills=s.spawned-1;s.enemies=[enemy(900+wave,0,-2)];s.player.x=0;s.player.z=0;s.cooldown=0;fireStone(s,0,-1);stepBattle(s,.05);assert.equal(s.phase,'intermission');const frozen=structuredClone(s);stepBattle(s,.05);assert.deepEqual(s,frozen);assert.equal(beginNextWave(s),true);assert.equal(s.enemies.length,waveRules(wave+1).initial);assert.equal(s.wave,wave+1);}});
test('intermission heals at most one and restart resets all counters',()=>{const s=createBattle();s.phase='intermission';s.enemies=[];s.player.hp=2;beginNextWave(s);assert.equal(s.player.hp,3);const b=createBattle();assert.equal(b.score,0);assert.equal(b.wave,1);assert.equal(b.player.hp,5);assert.equal(b.shots,0);});

test('unmodified survival strategy passes third wave then reaches grace after exhaustion',()=>{for(const seed of [1,12,123,999]){const s=createBattle(seed);for(let frame=0;frame<24000&&s.phase!=='grace'&&s.phase!=='complete';frame++){if(s.phase==='intermission'){beginNextWave(s);continue;}const p=s.player,target=[...s.enemies].sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0],a=s.time*.43;stepBattle(s,.025,{moveX:Math.cos(a)*10-p.x,moveZ:Math.sin(a)*10-p.z,aimX:(target?.x??0)-p.x,aimZ:(target?.z??0)-p.z,firing:!!target});}assert.equal(s.phase,'grace');assert.ok(s.wave>=4);assert.ok(s.kills>=72);assert.equal(s.player.hp,0);advance(s,5);assert.equal(s.phase,'complete');assert.equal(s.enemies.length,0);}});

test('contact knockback never pushes giants outside playable boundary',()=>{const s=createBattle();s.player.x=18;s.player.z=0;s.enemies=[enemy(900,18.2,0)];stepBattle(s,.025);assert.ok(Math.hypot(s.enemies[0].x,s.enemies[0].z)<=RULES.arena);});
test('combo ends on damage, dash recharges, wave counts reset independently',()=>{const s=createBattle();s.combo=12;s.comboTimer=3;s.enemies=[enemy(900,0,0)];stepBattle(s,.025);assert.equal(s.combo,0);dash(s,1,0);s.player.invulnerable=10;advance(s,3.1);assert.equal(dash(s,1,0),true);s.phase='intermission';s.enemies=[];s.kills=18;s.waveKills=18;beginNextWave(s);assert.equal(s.kills,18);assert.equal(s.waveKills,0);});

test('endless regression: third wave is not victory and fourth wave starts',()=>{const s=createBattle();s.wave=3;s.spawned=30;s.waveKills=30;s.enemies=[];stepBattle(s,.025);assert.equal(s.phase,'intermission');assert.equal(beginNextWave(s),true);assert.equal(s.wave,4);assert.equal(s.phase,'playing');});

test('difficulty grows while simulation rates remain bounded',()=>{let prev=waveRules(1);for(let wave=2;wave<=1000;wave++){const cur=waveRules(wave);assert.ok(cur.count>prev.count);assert.ok(cur.initial>=prev.initial&&cur.initial<=RULES.maxEnemies);assert.ok(cur.spawnInterval<=prev.spawnInterval&&cur.spawnInterval>=.18);assert.ok(cur.speedMultiplier>=prev.speedMultiplier&&cur.speedMultiplier<=4);assert.ok(cur.hpBonus>=prev.hpBonus);prev=cur;}assert.ok(waveRules(4).hpBonus>waveRules(1).hpBonus);});
test('high waves apply added HP and speed to actual enemies',()=>{const low=createBattle(),high=createBattle();high.phase='intermission';high.enemies=[];high.wave=9;beginNextWave(high);for(const e of high.enemies)assert.equal(e.maxHp,SINS.find(s=>s.id===e.sinId).hp+3);low.enemies=[enemy(999,0,-10)];high.enemies=[enemy(999,0,-10)];stepBattle(low,.025);stepBattle(high,.025);assert.ok(high.enemies[0].z>low.enemies[0].z);});
test('high waves bound simultaneous enemies and resume queue when slots free',()=>{const s=createBattle();s.phase='intermission';s.wave=99;s.enemies=[];beginNextWave(s);s.player.invulnerable=100;advance(s,30);assert.equal(s.enemies.length,RULES.maxEnemies);assert.equal(s.spawned,RULES.maxEnemies);assert.ok(s.spawned<waveRules(s.wave).count);s.enemies.pop();advance(s,.25);assert.equal(s.enemies.length,RULES.maxEnemies);assert.equal(s.spawned,RULES.maxEnemies+1);});
