import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createKeilahService} from '../server/keilah-service.mjs';
function fixture({clock={t:0},service}={}){const s=service||createKeilahService({now:()=>clock.t});const a=s.create(randomUUID()),b=s.join(a.state.code,randomUUID()),code=a.state.code;const tokens=[a.token,b.token];const read=i=>s.read(code,tokens[i]);const cmd=(i,action,to)=>{const st=read(i);return s.command(code,tokens[i],{run:st.run,seq:st.players[i].seq+1,action,...(to?{to}:{})});};const advance=(ms,heartbeat=true)=>{for(let n=0;n<ms;n+=100){clock.t+=Math.min(100,ms-n);if(heartbeat){read(0);read(1);}else s.tick();}};const move=(i,to)=>{cmd(i,'move',to);const j=read(i).players[i].job;advance(j.end-clock.t);assert.equal(read(i).players[i].node,to);};const rescue=i=>{cmd(i,'rescue');advance(14000);};const start=()=>{cmd(0,'ready');cmd(1,'ready');};return {s,a,b,code,tokens,read,cmd,advance,move,rescue,start,clock,setTime:v=>{clock.t=v;}};}
function finish(f){const {cmd,advance,read}=f;const both=(a,b)=>{cmd(0,'move',a);cmd(1,'move',b);const x=read(0),y=read(1);advance(Math.max(x.players[0].job.end,y.players[1].job.end)-x.serverNow);};f.start();both('square','square');both('west','east');cmd(1,'hold');f.move(0,'wgate');f.move(0,'west');cmd(0,'hold');cmd(1,'release');f.move(1,'egate');cmd(0,'release');f.move(0,'wgate');for(const suffix of ['1','2']){both('w'+suffix,'e'+suffix);cmd(0,'rescue');cmd(1,'rescue');advance(14000);assert.throws(()=>cmd(0,'rescue'),/escort_first/);both('wgate','egate');both('west','east');both('square','square');both('exit','exit');if(suffix==='1'){both('square','square');both('west','east');both('wgate','egate');}}cmd(0,'escape');assert.equal(read(0).phase,'playing');return cmd(1,'escape');}
test('full cooperative rescue is server timed, four families + both exits and role swap; one record; retry resets',()=>{const f=fixture(),st=finish(f);assert.equal(st.phase,'complete');assert.equal(st.eligible,true);assert.ok(st.elapsed>=180000&&st.elapsed<=300000);assert.equal(f.s.ranking().entries.length,1);f.s.tick();assert.equal(f.s.ranking().entries.length,1);const oldRun=st.run;f.cmd(0,'retry');assert.equal(f.read(1).phase,'lobby');assert.equal(f.read(1).run,oldRun+1);assert.equal(f.read(1).players[1].rescued,0);});
test('two members only; duplicate create/join are idempotent; capabilities are not disclosed',()=>{const s=createKeilahService(),id=randomUUID(),a=s.create(id);assert.deepEqual(s.create(id),a);const jid=randomUUID(),b=s.join(a.state.code,jid);assert.deepEqual(s.join(a.state.code,jid),b);assert.throws(()=>s.join(a.state.code,randomUUID()),/room_full/);assert.ok(!JSON.stringify(s.read(a.state.code,a.token)).includes(b.token));assert.ok(!JSON.stringify(s.read(a.state.code,a.token)).includes('secret'));});
test('room isolation, no third player, no forged score or teleport',()=>{const f=fixture(),other=f.s.create(randomUUID());assert.throws(()=>f.s.read(f.code,other.token),/not_a_member/);f.start();assert.throws(()=>f.cmd(0,'move','w2'),/not_adjacent/);assert.throws(()=>f.cmd(0,'finish'),/unknown_action/);assert.throws(()=>f.cmd(0,'escape'),/rescue_everyone_first/);assert.equal(f.s.ranking().entries.length,0);});
test('one ready cannot start; replayed ready does not toggle; old run and sequence gaps rejected',()=>{const f=fixture();const input={run:1,seq:1,action:'ready'};f.s.command(f.code,f.tokens[0],input);f.s.command(f.code,f.tokens[0],input);assert.equal(f.read(0).phase,'lobby');assert.equal(f.read(0).players[0].ready,true);assert.throws(()=>f.s.command(f.code,f.tokens[0],{run:0,seq:2,action:'ready'}),/stale_run/);assert.throws(()=>f.s.command(f.code,f.tokens[0],{run:1,seq:3,action:'ready'}),/sequence_gap/);});
test('crossing requires the other player continuously; release cancels crossing; rescue takes server time',()=>{const f=fixture();f.start();f.move(0,'square');f.move(0,'west');assert.throws(()=>f.cmd(0,'move','wgate'),/partner_must_hold/);f.move(1,'square');f.move(1,'east');f.cmd(1,'hold');f.cmd(0,'move','wgate');f.advance(5000);f.cmd(1,'release');f.advance(100);assert.equal(f.read(0).players[0].node,'west');assert.equal(f.read(0).players[0].job,null);f.cmd(1,'hold');f.move(0,'wgate');f.move(0,'w1');f.cmd(0,'rescue');f.advance(13900);assert.equal(f.read(0).families.w1,null);f.advance(100);assert.equal(f.read(0).families.w1,0);});
test('brief refresh keeps slot, long disconnection pauses and disqualifies, 60 seconds ends; no score',()=>{const f=fixture();f.start();f.advance(5000,false);assert.equal(f.read(0).eligible,true);f.read(1);f.advance(9000,false);assert.equal(f.read(0).paused,true);assert.equal(f.read(0).eligible,false);assert.equal(f.read(1).paused,false);f.advance(61000,false);assert.equal(f.read(0).phase,'ended');assert.equal(f.s.ranking().entries.length,0);});
test('leaving ends both players run; token invalidated, retry allows replacement, no abandoned room leak',()=>{const f=fixture();f.start();f.cmd(1,'leave');assert.equal(f.read(0).phase,'ended');assert.throws(()=>f.read(1),/not_a_member/);f.cmd(0,'retry');const c=f.s.join(f.code,randomUUID());assert.equal(c.state.slot,1);f.advance(31*60000,false);assert.equal(f.s.stats().rooms,0);});
test('server stall removes ranking eligibility; bounded room capacity',()=>{const f=fixture();f.start();f.setTime(3000);f.s.tick();assert.equal(f.read(0).eligible,false);const s=createKeilahService({maxRooms:1});s.create(randomUUID());assert.throws(()=>s.create(randomUUID()),/rooms_full/);});

test('independent teams compete on the same server and only completed runs enter top ten',()=>{const a=fixture();finish(a);const b=fixture({clock:a.clock,service:a.s});finish(b);const rows=a.s.ranking().entries;assert.equal(rows.length,2);assert.notEqual(rows[0].team,rows[1].team);assert.ok(rows[0].timeMs<=rows[1].timeMs);assert.ok(rows.every(r=>r.map==='keilah-1'));});
