import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {openKeilahDb,invoke,serviceFactory,testEnv,KEILAH_MIGRATION} from '../scripts/fixtures/keilah-db.mjs';
import {createKeilahOnlineHandler} from '../server/keilah-online-http.mjs';
import {NODES,EDGES} from '../src/keilah-map.js';
const key='a'.repeat(64),hash=s=>createHash('sha256').update(s).digest('hex');
async function fixture(t,{clock=true}={}){
 let db,time=Date.now();
 if(clock){
  db=new PGlite();await db.exec('CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO anon,authenticated;CREATE SCHEMA keilah_test;CREATE TABLE keilah_test.clock(value timestamptz);INSERT INTO keilah_test.clock VALUES(clock_timestamp());CREATE FUNCTION keilah_test.now() RETURNS timestamptz LANGUAGE sql AS $$SELECT value FROM keilah_test.clock$$;GRANT USAGE ON SCHEMA keilah_test TO service_role;GRANT SELECT,UPDATE ON keilah_test.clock TO service_role;');
  // Deterministic clock only in this isolated unit fixture. The browser/restart suite uses the unchanged migration.
  await db.exec((await fs.readFile(KEILAH_MIGRATION,'utf8')).replaceAll('clock_timestamp()','keilah_test.now()'));await db.exec('SET ROLE service_role');await db.query('UPDATE keilah_test.clock SET value=to_timestamp($1/1000.0)',[time]);
 }else db=await openKeilahDb();
 t.after(()=>db.close());
 const makeService=()=>serviceFactory(db)({url:testEnv.CHALLENGE_SUPABASE_URL,secretKey:testEnv.CHALLENGE_SUPABASE_SECRET_KEY});
 const s=makeService();const a=await s.enter('create',{requestId:randomUUID()},key),code=a.state.code,b=await s.enter('join',{code,requestId:randomUUID()},key);const tokens=[a.token,b.token];
 const read=i=>makeService().read(code,tokens[i],key);
 const cmd=async(i,action,to)=>{const st=await read(i);return makeService().command(code,tokens[i],{seq:st.players[i].seq+1,run:st.run,action,...(action==='ready'?{consent:true}:{}),...(to?{to}:{})},key);};
 const advance=async(ms,heartbeat=true)=>{for(let n=0;n<ms;n+=1000){time+=Math.min(1000,ms-n);await db.query('UPDATE keilah_test.clock SET value=to_timestamp($1/1000.0)',[time]);if(heartbeat){await read(0);await read(1);}}};
 const both=async(x,y)=>{await Promise.all([cmd(0,'move',x),cmd(1,'move',y)]);const a=await read(0),b=await read(1);await advance(Math.max(a.players[0].job.end,b.players[1].job.end)-time);};
 const move=async(i,to)=>{await cmd(i,'move',to);const st=await read(i);await advance(st.players[i].job.end-time);};
 return {db,s,makeService,read,cmd,advance,both,move,code,tokens,a,b,start:async()=>{await Promise.all([cmd(0,'ready'),cmd(1,'ready')]);}};
}
async function finish(f){await f.start();await f.both('square','square');await f.both('west','east');await f.cmd(1,'hold');await f.move(0,'wgate');await f.move(0,'west');await f.cmd(0,'hold');await f.cmd(1,'release');await f.move(1,'egate');await f.cmd(0,'release');await f.move(0,'wgate');
 for(const n of ['1','2']){await f.both('w'+n,'e'+n);await Promise.all([f.cmd(0,'rescue'),f.cmd(1,'rescue')]);await f.advance(14000);await assert.rejects(f.cmd(0,'rescue'),/escort_first/);await f.both('wgate','egate');await f.both('west','east');await f.both('square','square');await f.both('exit','exit');if(n==='1'){await assert.rejects(f.cmd(0,'escape'),/rescue_everyone_first/);await f.both('square','square');await f.both('west','east');await f.both('wgate','egate');}}
 await f.cmd(0,'escape');assert.equal((await f.read(1)).phase,'playing');return f.cmd(1,'escape');
}
test('SQL course parity and complete two-person rescue; stateless service instances; one persisted record',async t=>{const f=await fixture(t);const course=(await f.db.query('select keilah_coop.course() AS c')).rows[0].c;assert.deepEqual(course,{nodes:NODES,edges:EDGES});const st=await finish(f);assert.equal(st.phase,'complete');assert.ok(st.elapsed>=180000&&st.elapsed<=300000);assert.ok(st.players.every(p=>p.escaped&&p.rescued===2&&p.opened>=1));assert.ok(Object.values(st.delivered).every(Boolean));assert.ok(!JSON.stringify(st).includes('secret'));const rank=await f.makeService().ranking(key);assert.equal(rank.entries.length,1);assert.match(rank.entries[0].team,/^T-[A-F0-9]{6}$/);assert.ok(!JSON.stringify(rank).includes(f.code));await f.cmd(1,'leave');assert.equal((await f.read(0)).phase,'complete');assert.equal((await f.s.ranking(key)).entries.length,1);});
test('private tables and invoker RPC reject anon/authenticated, including permissive default function grants',async t=>{const f=await fixture(t,{clock:false});for(const role of ['anon','authenticated']){await f.db.exec('RESET ROLE;SET ROLE '+role);await assert.rejects(f.db.query('select public.keilah_coop_rpc($1,$2,$3)',['ranking','{"version":"keilah-1"}',key]),/permission denied/);await assert.rejects(f.db.query('select * from keilah_coop.rooms'),/permission denied/);}await f.db.exec('RESET ROLE');const checks=(await f.db.query("SELECT c.relname,c.relrowsecurity FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='keilah_coop' AND c.relkind='r'")).rows;assert.equal(checks.length,3);assert.ok(checks.every(c=>c.relrowsecurity));const def=(await f.db.query("select prosecdef from pg_proc where proname='keilah_coop_rpc'")).rows[0];assert.equal(def.prosecdef,false);});
test('racing joins and duplicate ready commands have exactly one effect; third member and wrong room token rejected',async t=>{const f=await fixture(t);const c=await f.s.enter('create',{requestId:randomUUID()},key);const joins=await Promise.allSettled([f.makeService().enter('join',{code:c.state.code,requestId:randomUUID()},key),f.makeService().enter('join',{code:c.state.code,requestId:randomUUID()},key)]);assert.equal(joins.filter(x=>x.status==='fulfilled').length,1);assert.equal(joins.find(x=>x.status==='rejected').reason.code,'room_full');await assert.rejects(f.s.read(c.state.code,f.tokens[0],key),/not_a_member/);const body={seq:1,run:1,action:'ready',consent:true};await Promise.all([f.s.command(f.code,f.tokens[0],body,key),f.makeService().command(f.code,f.tokens[0],body,key)]);assert.equal((await f.read(0)).players[0].ready,true);await assert.rejects(f.s.command(f.code,f.tokens[0],{...body,consent:false},key),/sequence_conflict/);});
test('lost entry response is recoverable across instances; revoked entry is not revived',async t=>{const f=await fixture(t);const id=randomUUID(),a=await f.s.enter('create',{requestId:id},key),again=await f.makeService().enter('create',{requestId:id},key);assert.equal(a.token,again.token);assert.equal(a.state.code,again.state.code);await f.s.command(a.state.code,a.token,{seq:1,run:1,action:'leave'},key);await assert.rejects(f.makeService().enter('create',{requestId:id},key),/request_expired/);});
test('forged clock/score/position, premature finish and absent consent are rejected by SQL',async t=>{const f=await fixture(t);await assert.rejects(f.s.command(f.code,f.tokens[0],{seq:1,run:1,action:'ready',consent:false},key),/consent_required/);await f.start();for(const extra of [{timeMs:1},{position:'w1'},{score:999}])await assert.rejects(f.s.command(f.code,f.tokens[0],{seq:2,run:1,action:'escape',...extra},key),/invalid_request/);await assert.rejects(f.cmd(0,'move','w2'),/not_adjacent/);await assert.rejects(f.cmd(0,'escape'),/rescue_everyone_first/);assert.equal((await f.s.ranking(key)).entries.length,0);});
test('12-second mobile grace pauses shared progress; resume counts outage time; 60-second loss ends run',async t=>{const f=await fixture(t);await f.start();await f.cmd(0,'move','square');await f.advance(5000,false);assert.ok((await f.read(0)).players[0].job);await f.advance(10000,false);let st=await f.read(0);assert.equal(st.paused,true);assert.equal(st.eligible,true);await f.read(1);assert.equal((await f.read(0)).paused,false);await f.advance(61000,false);assert.equal((await f.read(0)).phase,'ended');assert.equal((await f.s.ranking(key)).entries.length,0);});
test('crossing and family progress pause during outage without creating free movement',async t=>{const f=await fixture(t);await f.start();await f.both('square','square');await f.both('west','east');await f.cmd(1,'hold');await f.cmd(0,'move','wgate');await f.advance(5000);await f.cmd(1,'release');await f.advance(1000);assert.equal((await f.read(0)).players[0].node,'west');await f.cmd(1,'hold');await f.move(0,'wgate');await f.move(0,'w1');await f.cmd(0,'rescue');await f.advance(20000,false);const st=await f.read(0);assert.equal(st.families.w1,null);assert.ok(st.players[0].job.end>st.serverNow);await f.read(1);await f.advance(2000);assert.equal((await f.read(0)).families.w1,0);});
test('leave invalidates membership; retry increments run and rejects old commands; expiry is enforced',async t=>{const f=await fixture(t);await f.start();await f.cmd(1,'leave');await assert.rejects(f.read(1),/not_a_member/);assert.equal((await f.read(0)).phase,'ended');const next=await f.cmd(0,'retry');assert.equal(next.run,2);await assert.rejects(f.s.command(f.code,f.tokens[0],{seq:3,run:1,action:'ready',consent:true},key),/stale_run/);await f.db.exec("UPDATE keilah_coop.rooms SET expires_at=timestamp '2000-01-01'");await assert.rejects(f.read(0),/room_not_found/);});
test('HTTP feature flag, rewrite dispatch, origin, exact input and capability boundary',async t=>{const f=await fixture(t,{clock:false});const handler=createKeilahOnlineHandler({env:testEnv,serviceFactory:serviceFactory(f.db)});const request=(route,body,extra={})=>new Request(testEnv.CHALLENGE_ALLOWED_ORIGIN+'/api/keilah?route='+route,{method:body?'POST':'GET',headers:{'x-vercel-forwarded-for':'203.0.113.1',...(body?{origin:testEnv.CHALLENGE_ALLOWED_ORIGIN,'content-type':'application/json'}:{}),...extra},body:body?JSON.stringify(body):undefined});assert.equal((await handler(request('config'))).status,200);assert.equal((await createKeilahOnlineHandler({env:{...testEnv,KEILAH_ONLINE_ENABLED:'false'}})(request('config'))).status,503);assert.equal((await handler(request('rooms',{requestId:randomUUID()},{origin:'https://evil.example'}))).status,403);assert.equal((await handler(request('rooms/'+f.code))).status,403);assert.equal((await handler(request('rooms/'+f.code+'/command',{seq:1,run:1,action:'ready',consent:true,score:1},{authorization:'Bearer '+f.tokens[0]}))).status,400);assert.equal((await handler(request('rooms',{requestId:randomUUID()},{'content-type':'text/plain'}))).status,415);});
test('unchanged migration and file-backed PostgreSQL survive complete database restart',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'keilah-persist-'));let db;try{db=await openKeilahDb(dir);let s=serviceFactory(db)({url:testEnv.CHALLENGE_SUPABASE_URL,secretKey:testEnv.CHALLENGE_SUPABASE_SECRET_KEY});const a=await s.enter('create',{requestId:randomUUID()},key);await db.close();db=await openKeilahDb(dir);s=serviceFactory(db)({url:testEnv.CHALLENGE_SUPABASE_URL,secretKey:testEnv.CHALLENGE_SUPABASE_SECRET_KEY});const state=await s.read(a.state.code,a.token,key);assert.equal(state.code,a.state.code);assert.equal(state.slot,0);}finally{await db?.close();await fs.rm(dir,{recursive:true,force:true});}});

test('migration is additive and leaves existing personal ranking rows and RPCs intact',async t=>{const db=new PGlite();t.after(()=>db.close());await db.exec('CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role BYPASSRLS;');await db.exec(await fs.readFile(new URL('../supabase/migrations/20261005074002_dance_engedi_top10.sql',import.meta.url),'utf8'));await db.exec("INSERT INTO dance_challenge.ranking_entries(initials,metric,consent_version) VALUES('ABC',900,'dance-side-top10-v1');INSERT INTO engedi_challenge.ranking_entries(initials,metric,consent_version) VALUES('DEF',2100,'engedi-side-top10-v1');CREATE SCHEMA sling_challenge;CREATE TABLE sling_challenge.preservation_probe(value integer);INSERT INTO sling_challenge.preservation_probe VALUES(74985)");await db.exec(await fs.readFile(KEILAH_MIGRATION,'utf8'));assert.equal((await db.query('SELECT metric FROM dance_challenge.ranking_entries')).rows[0].metric,900);assert.equal((await db.query('SELECT metric FROM engedi_challenge.ranking_entries')).rows[0].metric,2100);assert.equal((await db.query('SELECT value FROM sling_challenge.preservation_probe')).rows[0].value,74985);assert.equal((await db.query("SELECT count(*)::integer n FROM pg_proc WHERE proname IN ('dance_challenge_rpc','engedi_challenge_rpc')")).rows[0].n,2);});
