import test from 'node:test';
import assert from 'node:assert/strict';
import { createOnlineChallengeHandler, challengeClientKey, readChallengeJson } from '../server/challenge-online-http.mjs';
import { ChallengeServiceError } from '../server/challenge-service.mjs';
const origin='https://game.example',id='a'.repeat(48);
// An inert test string, never a real credential.
const env={VERCEL:'1',CHALLENGE_ONLINE_ENABLED:'true',CHALLENGE_ALLOWED_ORIGIN:origin,CHALLENGE_SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',CHALLENGE_SUPABASE_SECRET_KEY:'sb_secret_inert_test_fixture'};
const request=(path='/record',body,extra={})=>new Request(origin+'/api/sling-challenge'+path,{method:body===undefined?'GET':'POST',headers:{'x-vercel-forwarded-for':'203.0.113.10',...(body===undefined?{}:{origin,'Content-Type':'application/json'}),...extra},body:body===undefined?undefined:JSON.stringify(body)});
function fixture(action,options={}){const calls=[];const result={mode:'online',onlineEligible:true,recordScope:'global',record:null};const serviceFactory=()=>Object.fromEntries(['getRecord','createAttempt','finishAttempt','submitRecord'].map(name=>[name,async(...args)=>{calls.push({name,args});return result;}]));return{calls,handler:createOnlineChallengeHandler(action,{env:{...env},serviceFactory,...options})};}
test('online route is disabled by default and cannot fall back to a mock',async()=>{const f=fixture('record',{env:{}});const r=await f.handler(request());assert.equal(r.status,503);assert.equal((await r.json()).mode,'unavailable');assert.equal(f.calls.length,0);});
test('read returns only service data with no cache/cookie/CORS grants',async()=>{const f=fixture('record');const r=await f.handler(request());assert.equal(r.status,200);assert.equal((await r.json()).recordScope,'global');assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('set-cookie'),null);assert.equal(r.headers.get('access-control-allow-origin'),null);assert.match(f.calls[0].args[0].clientKey,/^[a-f0-9]{64}$/);});
test('daily rate keys are consistent across instances and do not expose raw IP',()=>{const r=request();const a=challengeClientKey(r,{env,now:()=>Date.UTC(2026,9,2)}),b=challengeClientKey(r,{env:{...env},now:()=>Date.UTC(2026,9,2,12)}),next=challengeClientKey(r,{env,now:()=>Date.UTC(2026,9,3)});assert.equal(a,b);assert.notEqual(a,next);assert.ok(!a.includes('203.0.113.10'));});
test('untrusted hosting or missing platform network header fails closed',async()=>{for(const config of [{...env,VERCEL:'0'},env]){const f=fixture('record',{env:config});const r=await f.handler(new Request(origin+'/api/sling-challenge/record'));assert.equal(r.status,503);assert.equal(f.calls.length,0);}});
test('cross-origin requests, absent POST origin and alternate hosts are rejected before service',async()=>{const f=fixture('attempts');for(const r of [request('/attempts',{}, {origin:'https://elsewhere.example'}),request('/attempts',{}, {origin:''}),request('/attempts',{}, {'sec-fetch-site':'cross-site'}),new Request('https://other.example/api/sling-challenge/attempts',{method:'POST',headers:{origin,'Content-Type':'application/json','x-vercel-forwarded-for':'203.0.113.10'},body:'{}'})]){assert.equal((await f.handler(r)).status,403);}assert.equal(f.calls.length,0);});
test('attempt issuance accepts only an empty JSON object',async()=>{const f=fixture('attempts');assert.equal((await f.handler(request('/attempts',{}))).status,201);assert.equal((await f.handler(request('/attempts',{seed:'chosen'}))).status,400);assert.equal((await f.handler(request('/attempts',[]))).status,400);assert.equal(f.calls.length,1);});
test('finish and submit capabilities travel only in JSON body and are stripped before service input',async()=>{for(const [action,payload,method]of [['finish',{shots:[],endedAtMs:33000},'finishAttempt'],['submit',{initials:'ABC',publicConsent:true},'submitRecord']]){const f=fixture(action);const r=request('/'+action,{attemptId:id,...payload});assert.ok(!r.url.includes(id));assert.equal((await f.handler(r)).status,200);assert.equal(f.calls[0].name,method);assert.equal(f.calls[0].args[0],id);assert.deepEqual(f.calls[0].args[1],payload);assert.equal((await f.handler(request('/'+action,{...payload}))).status,404);}});
test('body limit, malformed JSON and content-type are checked before database writes',async()=>{const f=fixture('attempts');assert.equal((await f.handler(request('/attempts',{}, {'content-length':'999999'}))).status,413);assert.equal((await f.handler(request('/attempts',{}, {'content-type':'text/plain'}))).status,415);assert.equal((await f.handler(new Request(origin+'/api/sling-challenge/attempts',{method:'POST',headers:{origin,'content-type':'application/json','x-vercel-forwarded-for':'203.0.113.10'},body:'{bad'}))).status,400);assert.equal(f.calls.length,0);});
test('streaming body cannot bypass byte limit by omitting content-length',async()=>{const r=new Request(origin,{method:'POST',headers:{'Content-Type':'application/json'},body:new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('x'.repeat(100)));c.close();}}),duplex:'half'});await assert.rejects(readChallengeJson(r,{maxBytes:10}),e=>e.status===413);});
test('rate errors expose bounded retry guidance without secrets',async()=>{const f=fixture('record',{serviceFactory:()=>({getRecord(){throw new ChallengeServiceError('rate_limited','Please wait',429,{retryAfterMs:1200});}})});const r=await f.handler(request());assert.equal(r.status,429);assert.equal(r.headers.get('retry-after'),'2');assert.equal((await r.json()).error.retryAfterMs,1200);});
test('unexpected backend errors never leak configuration or raw messages',async()=>{const f=fixture('record',{serviceFactory:()=>{throw new Error(env.CHALLENGE_SUPABASE_SECRET_KEY);}});const r=await f.handler(request());assert.equal(r.status,503);assert.ok(!(await r.text()).includes('inert_test_fixture'));});
