import * as THREE from 'three';
import {GLTFLoader} from '../vendor/GLTFLoader.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {RoomEnvironment} from './vendor/RoomEnvironment.js';
import {buildPalace} from './palace.js';
const $=id=>document.getElementById(id),canvas=$('scene');
const r=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});r.setPixelRatio(Math.min(devicePixelRatio,1.5));r.setSize(innerWidth,innerHeight);r.outputColorSpace=THREE.SRGBColorSpace;r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=.86;r.shadowMap.enabled=true;r.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color('#b7b4a0');
const pmrem=new THREE.PMREMGenerator(r),room=new RoomEnvironment(r),env=pmrem.fromScene(room,.05);scene.environment=env.texture;room.dispose();pmrem.dispose();
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.06,150);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.maxDistance=28;controls.minDistance=2;controls.maxPolarAngle=Math.PI*.49;
const sun=new THREE.DirectionalLight(0xffe4b0,2.0);sun.position.set(-7,15,3);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-18,right:18,top:18,bottom:-18,near:.1,far:55});sun.shadow.normalBias=.035;scene.add(sun);scene.add(new THREE.HemisphereLight(0xc8d5e0,0x665138,.65));
const set=new THREE.Group(),actors=new THREE.Group();scene.add(set,actors);
const loader=new GLTFLoader(),clock=new THREE.Clock();let mixer,walk,idle,model,walking=false,phase=0,mode='a',view=0,baked=null,ready=false,last=performance.now(),frames=[];
const poses=[{pos:[2.7,2.5,7.5],look:[0,1.35,-2.4]},{pos:[-4.5,2.8,6.5],look:[.2,1.5,-2]},{pos:[0,2.7,10.5],look:[0,1.8,-3]}];
function setView(){camera.position.fromArray(poses[view].pos);controls.target.fromArray(poses[view].look);controls.update();if(mode==='b')bake();}
function normalize(root,height){const bounds=new THREE.Box3().setFromObject(root);const size=bounds.getSize(new THREE.Vector3());root.scale.multiplyScalar(height/size.y);root.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(root),center=b.getCenter(new THREE.Vector3());root.position.add(new THREE.Vector3(-center.x,-b.min.y,-center.z));return size;}
const bgScene=new THREE.Scene(),bgCamera=new THREE.Camera();const bgMat=new THREE.ShaderMaterial({depthTest:true,depthWrite:true,uniforms:{colorMap:{value:null},depthMap:{value:null}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}',fragmentShader:`uniform sampler2D colorMap;uniform sampler2D depthMap;varying vec2 vUv;void main(){gl_FragColor=texture2D(colorMap,vUv);gl_FragDepth=texture2D(depthMap,vUv).r;
#include <tonemapping_fragment>
#include <colorspace_fragment>
}`});const quad=new THREE.Mesh(new THREE.PlaneGeometry(2,2),bgMat);quad.frustumCulled=false;bgScene.add(quad);
function bake(){const size=r.getDrawingBufferSize(new THREE.Vector2());if(baked){baked.depthTexture.dispose();baked.dispose();}baked=new THREE.WebGLRenderTarget(size.x,size.y,{type:THREE.HalfFloatType});baked.samples=4;baked.depthTexture=new THREE.DepthTexture(size.x,size.y,THREE.UnsignedIntType);actors.visible=false;set.visible=true;r.setRenderTarget(baked);r.render(scene,camera);r.setRenderTarget(null);actors.visible=true;bgMat.uniforms.colorMap.value=baked.texture;bgMat.uniforms.depthMap.value=baked.depthTexture;window.MOCK.bakes++;}
function setMode(next){mode=next;controls.enabled=mode==='a';$('mode-a').setAttribute('aria-pressed',String(mode==='a'));$('mode-b').setAttribute('aria-pressed',String(mode==='b'));$('mode-name').textContent=mode==='a'?'A · 실제 3D 자산':'B · 고정 배경 + 3D 인물';$('description').textContent=mode==='a'?'기존 조립식 모델 대신 실제 메시·텍스처 자산을 로드합니다. 드래그로 시점을 바꾸고, 바닥을 클릭해 인물을 이동할 수 있습니다.':'배경의 색과 깊이를 한 번 저장한 뒤, 움직이는 인물만 3D로 렌더합니다. 기둥 뒤 가림도 깊이 정보로 처리합니다. 자유 카메라는 제한됩니다.';if(mode==='b'){const damping=controls.enableDamping;controls.enableDamping=false;controls.update();controls.enableDamping=damping;bake();}set.visible=true;window.MOCK.mode=mode;}
window.MOCK={ready:false,bakes:0,mode:'a',metrics:{},scene,camera,renderer:r};
let target=new THREE.Vector3(0,0,0);const ray=new THREE.Raycaster(),floorPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let down=null;
canvas.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];});canvas.addEventListener('pointerup',e=>{if(!ready||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;ray.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const hit=new THREE.Vector3();if(ray.ray.intersectPlane(floorPlane,hit)){target.set(THREE.MathUtils.clamp(hit.x,-2.1,2.1),0,THREE.MathUtils.clamp(hit.z,-5,4));walking=true;setAnimation(true);}});
function setAnimation(on){const next=on?walk:idle,prev=on?idle:walk;if(next){next.reset().fadeIn(.2).play();prev?.fadeOut(.2);}}
$('mode-a').onclick=()=>ready&&setMode('a');$('mode-b').onclick=()=>ready&&setMode('b');$('view').onclick=()=>{view=(view+1)%poses.length;setView();};$('reset').onclick=()=>{view=0;setView();};$('move').onclick=()=>{if(!ready)return;walking=!walking;if(walking)target.set(model.position.x>0?-1.5:1.5,0,model.position.z>0?-2.5:2.5);setAnimation(walking);};
addEventListener('resize',()=>{r.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();if(ready&&mode==='b')bake();});
try{
 const manifest=await fetch('./manifest.json').then(x=>{if(!x.ok)throw Error('Missing asset manifest');return x.json();});
 const architecture=manifest.environment?await loader.loadAsync(manifest.environment):{scene:await buildPalace(loader,manifest.environmentAssets)};set.add(architecture.scene);
 if(manifest.environment){const eb=new THREE.Box3().setFromObject(architecture.scene),es=eb.getSize(new THREE.Vector3());architecture.scene.scale.setScalar((manifest.environmentSpan||25)/Math.max(es.x,es.z));if(manifest.rotateEnvironment)architecture.scene.rotation.y=manifest.rotateEnvironment;architecture.scene.updateMatrixWorld(true);const nb=new THREE.Box3().setFromObject(architecture.scene),nc=nb.getCenter(new THREE.Vector3());architecture.scene.position.add(new THREE.Vector3(-nc.x,-nb.min.y,-nc.z));}
 architecture.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});
 const human=await loader.loadAsync(manifest.character);const visual=human.scene;normalize(visual,1.8);model=new THREE.Group();model.add(visual);actors.add(model);model.position.set(0,0,1.3);visual.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});
 mixer=new THREE.AnimationMixer(visual);const clips=human.animations;const idleClip=clips.find(c=>/idle|stand/i.test(c.name))||clips[0];const walkClip=clips.find(c=>/walk/i.test(c.name))||clips.find(c=>/run/i.test(c.name));idle=idleClip?mixer.clipAction(idleClip):null;walk=walkClip?mixer.clipAction(walkClip):null;idle?.play();mixer.update(.01);scene.updateMatrixWorld(true);visual.position.y-=new THREE.Box3().setFromObject(visual,true).min.y;
 const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const ctx=shadowCanvas.getContext('2d'),g=ctx.createRadialGradient(64,64,4,64,64,62);g.addColorStop(0,'rgba(12,8,4,.36)');g.addColorStop(1,'rgba(12,8,4,0)');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);const shadow=new THREE.Mesh(new THREE.PlaneGeometry(1.35,1.35),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.04;model.add(shadow);
 if(manifest.note)$('asset-note').textContent=manifest.note;
 window.MOCK.clips=clips.map(c=>c.name);window.MOCK.character=model;window.MOCK.assets=manifest;setView();ready=true;window.MOCK.ready=true;setMode('a');$('loading').remove();
}catch(e){$('loading').textContent='자산 로딩 실패: '+e.message;console.error(e);}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(mode==='a')controls.update();if(ready){if(walking){const d=target.clone().sub(model.position);d.y=0;if(d.length()<.05){walking=false;setAnimation(false);}else{const step=Math.min(d.length(),dt*1.1);d.normalize();model.position.addScaledVector(d,step);model.rotation.y=Math.atan2(d.x,d.z);}}mixer?.update(dt);let calls=0,triangles=0;if(mode==='b'&&baked){r.autoClear=true;r.render(bgScene,bgCamera);calls+=r.info.render.calls;triangles+=r.info.render.triangles;const old=scene.background;scene.background=null;set.visible=false;r.autoClear=false;r.render(scene,camera);set.visible=true;scene.background=old;r.autoClear=true;}else{set.visible=true;r.render(scene,camera);}calls+=r.info.render.calls;triangles+=r.info.render.triangles;const now=performance.now();frames.push(now-last);last=now;if(frames.length>120)frames.shift();window.MOCK.metrics={calls,triangles,frameMs:frames.reduce((a,b)=>a+b,0)/frames.length};$('stats').textContent=`${mode==='a'?'3D SCENE':'CACHED BACKGROUND'} · ${calls} draws · ${triangles.toLocaleString()} triangles`;}}
animate();
