import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:44936';if(!['127.0.0.1','localhost'].includes(new URL(base).hostname))throw Error('Local prototype only');
const out='test-results/keilah';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=metal']});
const baseline=await (await fetch(base+'/api/keilah/ranking')).json();
const checks=[],errors=[],requests=[];const check=async(name,fn)=>{await fn();checks.push(name);console.log('PASS',name);};
const context=async width=>{const c=await browser.newContext({viewport:{width,height:width===320?740:844},hasTouch:true,isMobile:true});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/'))requests.push({method:r.method(),path:new URL(r.url()).pathname});});await p.goto(base+'/keilah.html');return {c,p};};
const state=p=>p.evaluate(async()=>{const s=JSON.parse(sessionStorage.getItem('keilah-session-v1'));return (await fetch('/api/keilah/rooms/'+s.code,{headers:{authorization:'Bearer '+s.token}})).json();});
const idle=p=>expect.poll(async()=>{const s=await state(p);return !!s.players[s.slot].job;},{timeout:40000,intervals:[250]}).toBe(false);
const move=async(p,to)=>{await idle(p);await p.locator(`[data-to="${to}"]`).tap();await expect.poll(async()=>{const s=await state(p);return s.players[s.slot].node;},{timeout:40000,intervals:[300]}).toBe(to);await idle(p);};
const rescue=async p=>{const s=await state(p),before=s.players[s.slot].rescued;await p.locator('#rescue').tap();await expect.poll(async()=>{const a=await state(p);return a.players[a.slot].rescued;},{timeout:20000,intervals:[300]}).toBe(before+1);};
try{
 const a=await context(390),b=await context(320),c=await context(1280);
 await check('390/320/desktop layouts and touch controls',async()=>{for(const x of [a,b,c]){assert.ok(await x.p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await x.p.screenshot({path:`${out}/entry-${await x.p.evaluate(()=>innerWidth)}.png`,fullPage:true});}});
 await check('double create, invite, independent session, two seats only',async()=>{
  await a.p.locator('#create').evaluate(el=>{el.click();el.click();});await expect(a.p.locator('#roomCode')).toHaveText(/^[A-F0-9]{8}$/);const code=await a.p.locator('#roomCode').innerText();await b.p.locator('#code').fill(code);await b.p.locator('#join').tap();await expect(b.p.locator('#members')).toContainText('2번');await c.p.locator('#code').fill(code);await c.p.locator('#join').click();await expect(c.p.locator('#notice')).toContainText('두 명');const sa=await state(a.p),sb=await state(b.p);assert.equal(sa.slot,0);assert.equal(sb.slot,1);assert.equal(sa.code,sb.code);await expect(a.p.locator('#members')).not.toContainText('입장 대기');await a.p.screenshot({path:`${out}/lobby-390.png`,fullPage:true});
 });
 await check('lobby refresh restores same seat; cancel leave; readiness keyboard',async()=>{const old=await state(b.p);await b.p.reload();await expect(b.p.locator('#roomCode')).toHaveText(old.code);assert.equal((await state(b.p)).slot,1);await a.p.click('#leave');await a.p.keyboard.press('Escape');await expect(a.p.locator('#confirm')).not.toBeVisible();await a.p.locator('#ready').focus();await a.p.keyboard.press('Enter');await expect(a.p.locator('#ready')).toHaveText('준비 취소');assert.equal((await state(a.p)).phase,'lobby');await b.p.locator('#ready').tap();await expect(a.p.locator('#play')).toBeVisible();});
 await check('full real-time cooperative route, role exchange and both exits',async()=>{
  await Promise.all([move(a.p,'square'),move(b.p,'square')]);await Promise.all([move(a.p,'west'),move(b.p,'east')]);
  await a.p.locator('[data-to=wgate]').tap();await expect(a.p.locator('#notice')).toContainText('동료가 반대편');
  await b.p.locator('#hold').tap();await expect(b.p.locator('#hold')).toHaveText('손잡이 놓기');
  await move(a.p,'wgate');await move(a.p,'west');
  await a.p.locator('#hold').tap();await b.p.locator('#hold').tap();await move(b.p,'egate');await a.p.locator('#hold').tap();await move(a.p,'wgate');
  for(const suffix of ['1','2']){
   await Promise.all([move(a.p,'w'+suffix),move(b.p,'e'+suffix)]);await Promise.all([rescue(a.p),rescue(b.p)]);
   assert.ok((await state(a.p)).players.every(p=>p.carrying));console.log('SPLIT RESCUE',suffix);
   if(suffix==='1'){await expect(a.p.locator('#position')).toContainText('가족 인솔 중');await a.p.locator('#play').scrollIntoViewIfNeeded();await a.p.screenshot({path:`${out}/split-390.png`,fullPage:true});await a.p.screenshot({path:`${out}/play-390.png`});await b.p.screenshot({path:`${out}/split-320.png`,fullPage:true});}
   await Promise.all([move(a.p,'wgate'),move(b.p,'egate')]);await Promise.all([move(a.p,'west'),move(b.p,'east')]);await Promise.all([move(a.p,'square'),move(b.p,'square')]);await Promise.all([move(a.p,'exit'),move(b.p,'exit')]);
   if(suffix==='1'){assert.equal((await state(a.p)).phase,'playing');await expect(a.p.locator('#escape')).toBeDisabled();await Promise.all([move(a.p,'square'),move(b.p,'square')]);await Promise.all([move(a.p,'west'),move(b.p,'east')]);await Promise.all([move(a.p,'wgate'),move(b.p,'egate')]);}
  }
  await a.p.locator('#escape').tap();assert.equal((await state(a.p)).phase,'playing');await b.p.locator('#escape').tap();await expect(a.p.locator('#resultTitle')).toHaveText('모두 함께 구출 성공');const sa=await state(a.p),sb=await state(b.p);assert.equal(sa.phase,'complete');assert.equal(sb.phase,'complete');assert.ok(sa.eligible);assert.ok(sa.elapsed>=180000&&sa.elapsed<=300000);assert.deepEqual(sa.families,sb.families);console.log('REAL COMPLETION',sa.elapsed);
  await a.p.locator('#play').scrollIntoViewIfNeeded();await a.p.screenshot({path:`${out}/complete-390.png`,fullPage:true});await b.p.screenshot({path:`${out}/complete-320.png`,fullPage:true});await fs.writeFile(out+'/completion.json',JSON.stringify(sa,null,2));
 });
 await check('server-only ranking, local separation and retry handshake',async()=>{await a.p.locator('#records summary').click();await a.p.locator('#ranking').click();await expect(a.p.locator('#rankingList li')).toHaveCount(Math.min(10,baseline.entries.length+1));await a.p.locator('#retry').tap();await expect(b.p.locator('#lobby')).toBeVisible();await expect(b.p.locator('#ready')).toHaveText('준비하기');await a.p.locator('#ready').tap();await b.p.locator('#ready').tap();await expect(a.p.locator('#play')).toBeVisible();});
 await check('network drop, reconnection, refresh during run and practice eligibility',async()=>{await b.c.setOffline(true);await expect(a.p.locator('#objective')).toContainText('동료를 기다려요',{timeout:15000});await b.c.setOffline(false);await expect(a.p.locator('#objective')).not.toContainText('동료를 기다려요',{timeout:10000});assert.equal((await state(a.p)).eligible,false);await b.p.reload();await expect(b.p.locator('#play')).toBeVisible();assert.equal((await state(b.p)).slot,1);});
 await check('explicit leave cancels partner; rejoin gets fresh capability; menu navigation stops room polling',async()=>{await b.p.locator('#leave').tap();await b.p.locator('#confirmLeave').tap();await expect(b.p.locator('#entry')).toBeVisible();await expect(a.p.locator('#resultTitle')).toHaveText('이번 구출전 종료');await a.p.locator('#retry').tap();await b.p.locator('#code').fill((await state(a.p)).code);await b.p.locator('#join').tap();await expect(b.p.locator('#lobby')).toBeVisible();await b.p.click('#back');await b.p.click('#confirmLeave');await b.p.waitForURL('**/?menu=challenge');await b.p.waitForFunction(()=>window.GAME?.mode==='title');await expect(b.p.locator('#bKeilah')).toBeVisible();const late=[];b.p.on('request',r=>{if(r.url().includes('/api/keilah/'))late.push(r.url());});await b.p.waitForTimeout(800);assert.deepEqual(late,[]);await b.p.goBack();await expect(b.p.locator('#entry')).toBeVisible();});
 await check('offline exit releases local session and responsive in-game layout',async()=>{await c.p.locator('#create').click();await expect(c.p.locator('#roomCode')).toHaveText(/^[A-F0-9]{8}$/);await c.c.setOffline(true);await expect(c.p.locator('#notice')).toContainText('서버 연결',{timeout:10000});await c.p.click('#leave');await c.p.click('#confirmLeave');await expect(c.p.locator('#entry')).toBeVisible();assert.equal(await c.p.evaluate(()=>sessionStorage.getItem('keilah-session-v1')),null);await c.c.setOffline(false);});
 assert.deepEqual(errors,[]);assert.ok(requests.every(r=>r.path.startsWith('/api/keilah/')));await fs.writeFile(out+'/report.json',JSON.stringify({checks,errors,requestCount:requests.length,scope:'local only; independent contexts at 390/320; real wall-clock completion'},null,2));console.log('PASS',checks.length,'browser checks');
}finally{for(const c of browser.contexts())await c.close();await browser.close();}
