import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:43872',baseline=process.env.BASELINE_URL||'http://127.0.0.1:43873';
const b=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--use-angle=metal']});const p=await b.newPage({viewport:{width:1440,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const collect=()=>({heights:Array.from(GAME.hg.d),colliders:GAME.colliders.map(c=>({...c})),bounds:[[0,0],[105,0],[-115,-90]].map(v=>GAME.ch.bound(...v)),player:GAME.player.pos.toArray(),actors:GAME.actors.length});
try{
 await p.goto(baseline+'/?review=gameplay&test=1');await p.waitForFunction(()=>window.GAME?.reviewReady);const before=await p.evaluate(collect);
 await p.goto(base+'/?review=gameplay&test=1');await p.waitForFunction(()=>window.GAME?.reviewReady);const after=await p.evaluate(collect);assert.deepEqual(after,before,'Height samples, collision bounds, spawn and actors must stay exactly equal');
 const initial=await p.evaluate(()=>({landmark:GAME.chapterVista.landscape.landmark.toArray(),stats:GAME.chapterVista.landscape.stats,pitch:GAME.cam.pitch}));
 await p.evaluate(()=>{GAME.reviewShot=null;GAME.paused=false;GAME.lock=false;GAME.cineOff();GAME.cineW=0;GAME.input.keys.add('KeyW');});await p.waitForFunction(start=>GAME.player.pos.distanceTo({x:start[0],y:start[1],z:start[2]})>.6,before.player);await p.evaluate(()=>GAME.input.keys.delete('KeyW'));
 const movement=await p.evaluate(()=>({position:GAME.player.pos.toArray(),ground:GAME.groundAt(GAME.player.pos.x,GAME.player.pos.z),arrivalActive:GAME.chapterVista.arrivalActive}));assert.equal(movement.arrivalActive,false);assert.ok(Math.abs(movement.position[1]-movement.ground)<.1);
 const resources=await p.evaluate(()=>{GAME.paused=true;const samples=[];for(let i=0;i<5;i++){GAME.loadWorld(1);GAME.mode='play';GAME.placePlayer(...GAME.ch.start);GAME.updateCamera(1);GAME.renderer.render(GAME.scene,GAME.camera);if(GAME.chapterVista)throw Error('Vista leaked to another chapter');GAME.loadWorld(0);GAME.placePlayer(...GAME.ch.start);GAME.updateCamera(1);GAME.renderer.render(GAME.scene,GAME.camera);samples.push({...GAME.renderer.info.memory,programs:GAME.renderer.info.programs.length});}return samples;});assert.deepEqual(resources.at(-1),resources.at(-2));
 const aim=await p.evaluate(()=>{const g=GAME;g.aiming=true;g.cam.yaw=1;g.cam.pitch=.15;g.updateCamera(1);g.renderer.render(g.scene,g.camera);return{arrival:g.chapterVista.arrivalActive,yaw:g.cam.yaw,pitch:g.cam.pitch,finite:g.camera.matrixWorld.elements.every(Number.isFinite)};});assert.equal(aim.arrival,false);assert.equal(aim.yaw,1);assert.equal(aim.pitch,.15);assert.ok(aim.finite);assert.deepEqual(errors,[]);
 const report={samePhysics:true,movement,initial,resources,aim,errors};console.log(JSON.stringify(report,null,2));if(process.env.REPORT_FILE)await fs.writeFile(process.env.REPORT_FILE,JSON.stringify(report,null,2));
}finally{await b.close();}
