import * as THREE from '../vendor/three.module.js';
import * as core from './bethlehem-water-core.js';
import {createBethlehemWorld} from './bethlehem-water-world.js';
import {createRadar,MODE_LABEL_KO} from './bethlehem-water-radar.js';
const {LAYOUT,createState,startGame,step,targetFor,resetGame}=core;
const $=id=>document.getElementById(id);
let difficulty='normal';
const makeState=()=>createState({difficulty});
const state=makeState();
let renderer,world,camera,scene,radar,paused=false,last=performance.now(),elapsed=0,previousPhase='intro',modalKind='',soundOn=false,audio=null,quality='standard',lastAnnouncedMode='patrol';
document.addEventListener('keydown',e=>{if(e.key!=='Tab'||$('modal').hidden)return;const buttons=Array.from($('modal').querySelectorAll('button:not([hidden])'));const first=buttons[0],lastButton=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();lastButton.focus();}else if(!e.shiftKey&&document.activeElement===lastButton){e.preventDefault();first.focus();}});
const keys=new Set(),touch={x:0,z:0,crouch:false,action:false,sprint:false};let stickPointer=null,stonePending=false;
const HELD_BUTTONS={crouch:'crouch',action:'action','sprint-btn':'sprint'};const heldPointers={crouch:null,action:null,sprint:null};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const CAMERA_ANGLE=Math.atan2(7,26),c=Math.cos(CAMERA_ANGLE),s=Math.sin(CAMERA_ANGLE);
const round=(n,d=2)=>Number.isFinite(n)?Math.round(n*10**d)/10**d:n;
const readSnapshot=()=>({
 phase:state.phase,
 player:{x:round(state.player.x),z:round(state.player.z),heading:round(state.player.heading,3),moving:!!state.player.moving,crouching:!!state.player.crouching,sprinting:!!state.player.sprinting},
 guard:(state.guards||[]).map(g=>({id:g.id,x:round(g.x),z:round(g.z),heading:round(g.heading||0,3),sightRange:g.sightRange,fovHalf:g.fovHalf,mode:g.mode||'patrol',suspicion:round(g.suspicion??0,3),lastSeen:g.lastSeen?{x:round(g.lastSeen.x),z:round(g.lastSeen.z)}:null,seeing:!!g.seeing,hearing:!!g.hearing})),
 alarm:round(state.alarm,3),
 fill:round(state.fill,3),
 carry:!!state.carrying,
 retries:state.retries,
 paused,
 noise:state.noise?{x:round(state.noise.x),z:round(state.noise.z),radius:round(state.noise.radius),ttl:round(state.noise.ttl,2),kind:state.noise.kind||null}:null,
 movementNoise:state.movementNoise?{x:round(state.movementNoise.x),z:round(state.movementNoise.z),radius:round(state.movementNoise.radius),kind:state.movementNoise.kind}:null,
 companions:state.companions.map(c=>({x:round(c.x),z:round(c.z)})),
 stones:state.stones??0,
 distractionCooldown:round(state.distractionCooldown??0,2),
 stats:state.stats?{...state.stats}:{},
 difficulty:state.difficulty||difficulty,
 time:round(state.time??0,2),
 checkpoint:state.checkpoint?{x:round(state.checkpoint.x),z:round(state.checkpoint.z)}:null,
 graceTimer:round(state.graceTimer??0,2),
 artStatus:world?.artStatus??'procedural',
});
// Read-only perception diagnostic for local input-driven QA. No state reference,
// movement, time stepping, completion or mutation capability is exposed.
window.bethlehemInspect=Object.freeze({sightAt(x,z,crouching=true){return state.guards.some(g=>core.guardSees(g,{x,z},crouching));}});
function clearInput(){keys.clear();touch.x=touch.z=0;touch.crouch=touch.action=touch.sprint=false;stonePending=false;for(const [id,p] of [['joystick',stickPointer]]){try{if(p!==null&&$(id)?.hasPointerCapture(p))$(id).releasePointerCapture(p);}catch{}}stickPointer=null;for(const key of Object.keys(heldPointers)){const id=key==='sprint'?'sprint-btn':key;try{if(heldPointers[key]!=null&&$(id)?.hasPointerCapture(heldPointers[key]))$(id).releasePointerCapture(heldPointers[key]);}catch{}heldPointers[key]=null;}$('stick').style.transform='';$('crouch')?.classList.remove('active');$('action')?.classList.remove('active');$('sprint-btn')?.classList.remove('active');}
// Filling changes the objective, not the player's intent to remain behind cover.
// Release only the water action; modal/blur/reset paths still clear all held input.
function clearActionInput(){keys.delete('KeyE');touch.action=false;const p=heldPointers.action;heldPointers.action=null;try{if(p!==null&&$('action').hasPointerCapture(p))$('action').releasePointerCapture(p);}catch{}$('action').classList.remove('active');}
function closeModal(){ $('modal').hidden=true;modalKind='';clearInput();}
function showModal(kind,kicker,title,body,label,fn){clearInput();modalKind=kind;$('modal-kicker').textContent=kicker;$('modal-title').textContent=title;$('modal-body').textContent=body;$('modal-action').textContent=label;$('modal-action').onclick=fn;$('modal-secondary').hidden=true;$('modal').hidden=false;requestAnimationFrame(()=>$('modal-action').focus());}
function showSource(){paused=true;showModal('source','성경 이야기와 각색','다윗과 세 용사의 이야기','사무엘하 23:13–17을 바탕으로 만들었습니다. 세 용사가 베들레헴 성문 곁 우물에서 물을 길어 돌아오지만, 다윗은 목숨을 건 이들의 물을 마시지 않고 여호와께 부어 드립니다.\n\n플레이어는 세 용사 중 한 사람입니다. 잠입 방식, 순찰병, 이동 경로, 새벽 풍경과 대사는 게임을 위한 각색이며, 실제 지형을 재현한 것이 아닙니다. 성경 내용은 직접 풀어 썼습니다.\n\n낮은 돌담은 웅크려야 시야를 막습니다. 수풀은 발각을 어렵게 할 뿐, 가까운 병사에게는 보입니다. 동료 둘은 이야기 연출이며 발각 판정은 조작 중인 용사만 받습니다.','이야기로 돌아가기',()=>{closeModal();paused=false;});}
function pauseGame(){if(['intro','ending','complete','caught'].includes(state.phase)||modalKind)return;paused=true;showModal('pause','잠시 쉬어 가기','여기서 기다릴게요','움직임과 순찰이 모두 멈췄습니다.','계속하기',()=>{closeModal();paused=false;});$('modal-secondary').hidden=false;$('modal-secondary').textContent='처음부터 다시';$('modal-secondary').onclick=()=>{resetGame(state);closeModal();paused=false;previousPhase='';};}
$('source-open').onclick=showSource;$('pause').onclick=pauseGame;
for(const btn of document.querySelectorAll('.diff-option')){btn.addEventListener('click',()=>{if(state.phase!=='intro')return;difficulty=btn.dataset.difficulty==='hard'?'hard':'normal';for(const b of document.querySelectorAll('.diff-option'))b.setAttribute('aria-pressed',String(b===btn));Object.assign(state,makeState());});}
$('start').onclick=()=>{clearInput();startGame(state);paused=false;cue(330,.15);};
function unlockAudio(){if(!audio){const Context=window.AudioContext||window.webkitAudioContext;if(Context)audio=new Context();}audio?.resume().catch(()=>{});}
function cue(freq=440,duration=.15){if(!soundOn||!audio)return;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,audio.currentTime);gain.gain.setValueAtTime(.045,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);osc.connect(gain).connect(audio.destination);osc.start();osc.stop(audio.currentTime+duration);osc.onended=()=>{osc.disconnect();gain.disconnect();};}
$('sound').onclick=()=>{soundOn=!soundOn;if(soundOn)unlockAudio();$('sound').textContent=soundOn?'소리 켬':'소리 끔';$('sound').setAttribute('aria-label',soundOn?'소리 끄기':'소리 켜기');$('sound').setAttribute('aria-pressed',String(soundOn));cue(392,.22);};
$('quality').onclick=()=>{quality=quality==='standard'?'low':'standard';$('quality').textContent=quality==='low'?'가벼운 화질':'표준 화질';renderer.setPixelRatio(quality==='low'?1:Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=quality==='standard';world.setQuality?.(quality);resize();};
window.addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();if(modalKind==='pause'||modalKind==='source')$('modal-action').click();else pauseGame();return;}if(e.code==='KeyQ'){if(!modalKind&&!paused&&!['intro','ending','complete','caught'].includes(state.phase)&&!e.repeat)stonePending=true;e.preventDefault();return;}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD','KeyE','ShiftLeft','ShiftRight'].includes(e.code)){if(!modalKind&&state.phase!=='intro'){e.preventDefault();if(e.repeat&&!keys.has(e.code))return;keys.add(e.code);}}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{clearInput();pauseGame();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();pauseGame();}});
const joystick=$('joystick');function stickMove(e){if(e.pointerId!==stickPointer)return;const r=joystick.getBoundingClientRect(),max=r.width*.31;const dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dy),scale=len>max?max/len:1;touch.x=dx*scale/max;touch.z=dy*scale/max;if(len<5)touch.x=touch.z=0;$('stick').style.transform='translate('+(dx*scale)+'px,'+(dy*scale)+'px)';}
joystick.addEventListener('pointerdown',e=>{if(stickPointer!==null||paused)return;e.preventDefault();stickPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);stickMove(e);});joystick.addEventListener('pointermove',stickMove);function stopStick(e){if(e.pointerId!==stickPointer)return;stickPointer=null;touch.x=touch.z=0;$('stick').style.transform='';}for(const evt of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(evt,stopStick);
for(const [id,key] of Object.entries(HELD_BUTTONS)){const el=$(id);if(!el)continue;el.addEventListener('pointerdown',e=>{if(paused||el.disabled)return;if(heldPointers[key]!==null)return;e.preventDefault();el.setPointerCapture(e.pointerId);heldPointers[key]=e.pointerId;touch[key]=true;el.classList.add('active');});const release=e=>{if(e.pointerId!==heldPointers[key])return;heldPointers[key]=null;touch[key]=false;el.classList.remove('active');};for(const evt of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(evt,release);}
$('stone-btn')?.addEventListener('click',()=>{if(paused||modalKind||['intro','ending','complete','caught'].includes(state.phase)||$('stone-btn').disabled)return;stonePending=true;});
function consumeDistract(){if(stonePending){stonePending=false;return true;}return false;}
function input(){let x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touch.x;let z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+touch.z;const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}return{x:x*c+z*s,z:z*c-x*s,crouch:touch.crouch||keys.has('ShiftLeft')||keys.has('ShiftRight'),action:touch.action||keys.has('KeyE'),sprint:touch.sprint||keys.has('Space'),distract:consumeDistract()};}
function resize(){if(!renderer)return;renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}
function phaseChanged(){if(state.phase==='return'&&previousPhase==='filling')clearActionInput();else if(!['filling','outbound'].includes(state.phase)||previousPhase==='intro')clearInput();const phase=state.phase;if(phase==='intro'){$('stealth-announce').textContent='';lastAnnouncedMode='patrol';}document.body.classList.toggle('playing',phase!=='intro');$('intro').hidden=phase!=='intro';$('hud').hidden=['intro','ending','complete'].includes(phase);$('controls').hidden=['intro','caught','ending','complete'].includes(phase);$('radar').hidden=['intro','ending','complete'].includes(phase);$('ending').hidden=phase!=='ending';$('pause').hidden=['intro','ending','complete','caught'].includes(phase);$('target-label').hidden=['intro','caught','ending','complete'].includes(phase);
 if(phase==='caught'){showModal('caught','세 용사는 함께 움직입니다','잠시 물러섰습니다','추격하던 병사가 가까이 다가왔습니다.\n돌담 뒤에서 시야를 끊고, 수색이 끝날 때까지 기다려 보세요.\n수풀 속에서도 너무 가까운 병사에게는 보입니다.','마지막 안전 지점에서 다시',()=>{closeModal();step(state,{x:0,z:0,crouch:false,action:true,sprint:false,distract:false},.016);clearInput();});cue(165,.2);}
 if(phase==='return'){cue(523,.4);$('toast').textContent='물을 길었습니다. 이제 동료들과 다윗에게 돌아가세요.';}
 if(phase==='ending'){closeModal();cue(392,.65);$('footnote').hidden=true;}
 if(phase==='complete'){showModal('complete','사무엘하 23:13–17','그 물은 마실 수 없었습니다.','다윗은 세 용사가 목숨을 걸고 가져온 물을\n여호와께 부어 드렸습니다.\n\n누군가의 헌신을 당연하게 여기고 있지는 않나요?','다시 길을 나서기',()=>{closeModal();resetGame(state);startGame(state);paused=false;previousPhase='';$('footnote').hidden=false;});$('modal-secondary').hidden=false;$('modal-secondary').textContent='다윗 게임으로 돌아가기';$('modal-secondary').onclick=()=>location.href='./?menu=challenge';}
 previousPhase=phase;
}
const targetVector=new THREE.Vector3(),look=new THREE.Vector3(0,1,-6),desired=new THREE.Vector3();
const COVER_LABEL_KO={exposed:'노출됨','low-cover':'낮은 엄폐물 뒤',concealed:'수풀 속 · 가까우면 발각',occluded:'시야 차단됨'};
function updateUI(){const phase=state.phase,target=targetFor(state)||LAYOUT.well;const dist=Math.hypot(state.player.x-target.x,state.player.z-target.z);const returning=phase==='return';$('phase-label').textContent=returning?'03 · 함께 돌아가는 길':phase==='filling'?'02 · 성문 곁 우물':'01 · 베들레헴으로';$('objective').textContent=returning?'다윗이 기다리는 곳으로 돌아가세요':phase==='filling'?'누르고 있으면 물을 긷습니다':'성문 곁 우물로 가세요';$('hint').textContent=returning?'물 때문에 움직임은 느려지고 소리는 커집니다. 돌아갈 경로를 고르세요.':'웅크리기만으로는 숨을 수 없습니다. 돌담 뒤나 수풀에서 시야를 끊으세요.';$('distance').textContent=Math.ceil(dist)+'m';$('alarm-fill').style.width=Math.min(100,state.alarm*100)+'%';
 const info=typeof core.stealthInfo==='function'?core.stealthInfo(state):null;
 if(info){const coverText=COVER_LABEL_KO[info.cover]||'들키지 않았어요';const modeText=MODE_LABEL_KO[info.mode];$('stealth-label').textContent=modeText&&info.mode!=='patrol'?`${coverText} · 병사 ${modeText}`:coverText;if(info.mode!==lastAnnouncedMode){if(info.mode==='alert')$('stealth-announce').textContent='병사가 추격합니다. 벽 뒤로 돌아 시야를 끊으세요.';else if(info.mode==='search'&&lastAnnouncedMode==='alert')$('stealth-announce').textContent='병사가 수색 중이에요.';else if(info.mode==='patrol')$('stealth-announce').textContent='병사가 순찰로 돌아갔습니다.';lastAnnouncedMode=info.mode;}}
 else{$('stealth-label').textContent=state.alarm>.55?'병사가 이쪽을 보고 있어요':state.player.crouching?'몸을 낮추고 있어요':'들키지 않았어요';}
 const noise=state.noise,footsteps=state.movementNoise;$('noise-label').hidden=!noise&&!footsteps;if(noise||footsteps){const sounds=[];if(noise?.kind==='stone')sounds.push(`돌 ${Math.round(noise.radius)}m`);if(footsteps)sounds.push(`발소리 ${Math.round(footsteps.radius)}m`);else if(noise&&noise.kind!=='stone')sounds.push(`발소리 ${Math.round(noise.radius)}m`);$('noise-label').textContent=`최대 소리 범위 · ${sounds.join(' / ')}`;}
 const stones=state.stones??0,cooldown=state.distractionCooldown??0;$('stone-label').textContent=`돌 ${stones}개`;$('cooldown-label').textContent=cooldown>0?`재사용 ${cooldown.toFixed(1)}s`:'';const stoneUsable=stones>0&&cooldown<=0&&['outbound','filling','return'].includes(phase);if($('stone-btn')){$('stone-btn').disabled=!stoneUsable;$('stone-count').textContent=String(stones);}
 $('water-status').hidden=!state.carrying;$('fill-ring').style.height=(state.fill*100)+'%';$('action').firstChild.textContent=returning?'물 전하기':'물 긷기';$('action').setAttribute('aria-label',returning?'다윗에게 물 전하기':'물 긷기 누르고 있기');$('action').disabled=!['outbound','filling','return'].includes(phase)||dist>(returning?3.5:2.5);$('crouch').classList.toggle('active',state.player.crouching);if(state.message)$('toast').textContent=({'well-filled':'물을 채웠습니다. 순찰이 빨라졌습니다. 다윗에게 돌아가세요.','stone-thrown':'돌을 던졌습니다. 소리를 들은 병사만 확인하러 갑니다.','spotted':'붙잡혔습니다. 마지막 안전 지점에서 다시 시작할 수 있습니다.','poured-out-to-the-lord':'다윗은 그 물을 여호와께 부어 드렸습니다.','complete':''})[state.message]||'';else if(dist<(returning?3.5:2.5))$('toast').textContent=returning?'물 전하기를 눌러 다윗에게 건네세요.':'물 긷기를 길게 누르세요. 가까이에서 멈추면 물을 담습니다.';else $('toast').textContent='';
 targetVector.set(target.x,2.8,target.z).project(camera);const x=(targetVector.x*.5+.5)*innerWidth,y=(-targetVector.y*.5+.5)*innerHeight;$('target-label').style.left=Math.max(45,Math.min(innerWidth-45,x))+'px';const markerTop=innerHeight<540?260:(innerWidth<650?395:250),markerBottom=Math.max(markerTop,innerHeight-(innerHeight<540?110:185));let anchorY=Math.max(markerTop,Math.min(markerBottom,y));const radarBounds=$('radar').getBoundingClientRect(),anchorX=Math.max(45,Math.min(innerWidth-45,x));if(!$('radar').hidden&&anchorX+24>radarBounds.left&&anchorX-24<radarBounds.right&&anchorY>radarBounds.top&&anchorY-48<radarBounds.bottom)anchorY=Math.min(markerBottom,radarBounds.bottom+54);$('target-label').style.top=anchorY+'px';$('target-label').firstChild.textContent=returning?'다윗 ':'우물 ';radar?.render(state);$('app').dataset.state=JSON.stringify(readSnapshot());
}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;if(!paused){elapsed+=dt;step(state,input(),dt);}if(state.phase!==previousPhase)phaseChanged();world.update(elapsed,paused?0:dt,state);
 const intro=state.phase==='intro',ending=['ending','complete'].includes(state.phase),portrait=innerWidth<650;let tx=state.player.x,tz=state.player.z;
 if(intro){desired.set(portrait?27:30,portrait?20:17,portrait?44:38);targetVector.set(0,3,-7);}else if(ending){desired.set(11,8,33);targetVector.set(0,1.8,23);}else{desired.set(tx+7,portrait?23:20,tz+(portrait?29:26));targetVector.set(tx,1,tz-4);}
 const damping=reduced?1:1-Math.exp(-dt*3);camera.position.lerp(desired,damping);look.lerp(targetVector,damping);camera.lookAt(look);renderer.render(scene,camera);updateUI();}
try{scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,240);camera.position.set(30,17,38);renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;world=createBethlehemWorld({scene,renderer,layout:LAYOUT});radar=createRadar({layout:LAYOUT,core});resize();addEventListener('resize',resize);$('loading').hidden=true;requestAnimationFrame(frame);}catch(error){console.error(error);window.bethlehemLoadFailed();$('loading-message').textContent='3D 화면을 열지 못했습니다. 최신 브라우저에서 다시 열어 주세요.';}
$('world').addEventListener('webglcontextlost',e=>{e.preventDefault();paused=true;clearInput();showModal('webgl','그래픽 연결이 끊겼어요','화면을 다시 불러와 주세요','이 에피소드는 별도로 저장되지 않습니다. 기존 다윗 게임 기록은 바뀌지 않습니다.','다시 불러오기',()=>location.reload());});
